"""Create all tables

Revision ID: b504233c1a0d
Revises:
Create Date: 2025-08-07 13:43:25.298452

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b504233c1a0d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("season", sa.String(length=20), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("order_start_date", sa.Date(), nullable=True),
        sa.Column("order_end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("seo_title", sa.String(length=200), nullable=True),
        sa.Column("seo_description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_collection_order_dates",
        "collections",
        ["order_start_date", "order_end_date"],
        unique=False,
    )
    op.create_index(
        "idx_collection_season_year",
        "collections",
        ["season", "year"],
        unique=False,
    )
    op.create_index(
        "idx_collection_status_published",
        "collections",
        ["status", "is_published"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collections_id"), "collections", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_collections_is_deleted"),
        "collections",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collections_is_published"),
        "collections",
        ["is_published"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collections_name"), "collections", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_collections_season"), "collections", ["season"], unique=False
    )
    op.create_index(
        op.f("ix_collections_slug"), "collections", ["slug"], unique=True
    )
    op.create_index(
        op.f("ix_collections_status"), "collections", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_collections_year"), "collections", ["year"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("firebase_uid", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("photo_url", sa.String(length=500), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_email_active", "users", ["email", "is_active"], unique=False
    )
    op.create_index(
        "idx_user_role_active", "users", ["role", "is_active"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_firebase_uid"), "users", ["firebase_uid"], unique=True
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_is_active"), "users", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_users_is_deleted"), "users", ["is_deleted"], unique=False
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column(
            "wholesale_price", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "retail_price", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("material_composition", sa.Text(), nullable=True),
        sa.Column("sustainability_features", sa.JSON(), nullable=True),
        sa.Column("care_instructions", sa.JSON(), nullable=True),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("fit_notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("seo_title", sa.String(length=200), nullable=True),
        sa.Column("seo_description", sa.String(length=500), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_product_category_featured",
        "products",
        ["category", "is_featured"],
        unique=False,
    )
    op.create_index(
        "idx_product_collection_status",
        "products",
        ["collection_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_category"), "products", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_products_collection_id"),
        "products",
        ["collection_id"],
        unique=False,
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(
        op.f("ix_products_is_deleted"),
        "products",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_is_featured"),
        "products",
        ["is_featured"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_name"), "products", ["name"], unique=False
    )
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_index(
        op.f("ix_products_status"), "products", ["status"], unique=False
    )
    op.create_table(
        "files",
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("hash_md5", sa.String(length=32), nullable=True),
        sa.Column("hash_sha256", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("last_accessed", sa.String(length=50), nullable=True),
        sa.Column("collection_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_file_collection", "files", ["collection_id"], unique=False
    )
    op.create_index(
        "idx_file_content_type", "files", ["content_type"], unique=False
    )
    op.create_index("idx_file_created", "files", ["created_at"], unique=False)
    op.create_index("idx_file_product", "files", ["product_id"], unique=False)
    op.create_index("idx_file_size", "files", ["size"], unique=False)
    op.create_index(
        op.f("ix_files_collection_id"),
        "files",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_files_content_type"), "files", ["content_type"], unique=False
    )
    op.create_index(
        op.f("ix_files_filename"), "files", ["filename"], unique=False
    )
    op.create_index(
        op.f("ix_files_hash_md5"), "files", ["hash_md5"], unique=False
    )
    op.create_index(
        op.f("ix_files_hash_sha256"), "files", ["hash_sha256"], unique=False
    )
    op.create_index(op.f("ix_files_id"), "files", ["id"], unique=False)
    op.create_index(
        op.f("ix_files_is_deleted"), "files", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_files_product_id"), "files", ["product_id"], unique=False
    )
    op.create_table(
        "product_variants",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=50), nullable=False),
        sa.Column("color_code", sa.String(length=7), nullable=True),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("available_sizes", sa.JSON(), nullable=True),
        sa.Column(
            "price_adjustment",
            sa.DECIMAL(precision=10, scale=2),
            nullable=True,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_variant_available",
        "product_variants",
        ["is_available"],
        unique=False,
    )
    op.create_index(
        "idx_variant_product_color",
        "product_variants",
        ["product_id", "color"],
        unique=False,
    )
    op.create_index(
        "idx_variant_sort",
        "product_variants",
        ["product_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_color"),
        "product_variants",
        ["color"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_id"),
        "product_variants",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_is_available"),
        "product_variants",
        ["is_available"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_is_deleted"),
        "product_variants",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_product_id"),
        "product_variants",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_sku"),
        "product_variants",
        ["sku"],
        unique=True,
    )
    op.create_table(
        "size_charts",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("chart_type", sa.String(length=20), nullable=True),
        sa.Column("sizes", sa.JSON(), nullable=False),
        sa.Column("measurement_unit", sa.String(length=10), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id"),
    )
    op.create_index(
        op.f("ix_size_charts_id"), "size_charts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_size_charts_is_deleted"),
        "size_charts",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "technical_drawings",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("view", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("format", sa.String(length=10), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tech_drawing_product_view",
        "technical_drawings",
        ["product_id", "view"],
        unique=False,
    )
    op.create_index(
        "idx_tech_drawing_sort",
        "technical_drawings",
        ["product_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technical_drawings_id"),
        "technical_drawings",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technical_drawings_is_deleted"),
        "technical_drawings",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technical_drawings_product_id"),
        "technical_drawings",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technical_drawings_view"),
        "technical_drawings",
        ["view"],
        unique=False,
    )
    op.create_table(
        "technical_specifications",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("is_expandable", sa.Boolean(), nullable=True),
        sa.Column("is_expanded_by_default", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tech_spec_product_type",
        "technical_specifications",
        ["product_id", "type"],
        unique=False,
    )
    op.create_index(
        "idx_tech_spec_sort",
        "technical_specifications",
        ["product_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technical_specifications_id"),
        "technical_specifications",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technical_specifications_is_deleted"),
        "technical_specifications",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technical_specifications_product_id"),
        "technical_specifications",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technical_specifications_type"),
        "technical_specifications",
        ["type"],
        unique=False,
    )
    op.create_table(
        "product_images",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.UUID(), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("alt", sa.String(length=200), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("format", sa.String(length=10), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["product_variants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_product_image_type_order",
        "product_images",
        ["product_id", "type", "sort_order"],
        unique=False,
    )
    op.create_index(
        "idx_variant_image_type_order",
        "product_images",
        ["variant_id", "type", "sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_images_id"), "product_images", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_product_images_is_deleted"),
        "product_images",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_images_product_id"),
        "product_images",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_images_type"),
        "product_images",
        ["type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_images_variant_id"),
        "product_images",
        ["variant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_product_images_variant_id"), table_name="product_images"
    )
    op.drop_index(op.f("ix_product_images_type"), table_name="product_images")
    op.drop_index(
        op.f("ix_product_images_product_id"), table_name="product_images"
    )
    op.drop_index(
        op.f("ix_product_images_is_deleted"), table_name="product_images"
    )
    op.drop_index(op.f("ix_product_images_id"), table_name="product_images")
    op.drop_index("idx_variant_image_type_order", table_name="product_images")
    op.drop_index("idx_product_image_type_order", table_name="product_images")
    op.drop_table("product_images")
    op.drop_index(
        op.f("ix_technical_specifications_type"),
        table_name="technical_specifications",
    )
    op.drop_index(
        op.f("ix_technical_specifications_product_id"),
        table_name="technical_specifications",
    )
    op.drop_index(
        op.f("ix_technical_specifications_is_deleted"),
        table_name="technical_specifications",
    )
    op.drop_index(
        op.f("ix_technical_specifications_id"),
        table_name="technical_specifications",
    )
    op.drop_index("idx_tech_spec_sort", table_name="technical_specifications")
    op.drop_index(
        "idx_tech_spec_product_type", table_name="technical_specifications"
    )
    op.drop_table("technical_specifications")
    op.drop_index(
        op.f("ix_technical_drawings_view"), table_name="technical_drawings"
    )
    op.drop_index(
        op.f("ix_technical_drawings_product_id"),
        table_name="technical_drawings",
    )
    op.drop_index(
        op.f("ix_technical_drawings_is_deleted"),
        table_name="technical_drawings",
    )
    op.drop_index(
        op.f("ix_technical_drawings_id"), table_name="technical_drawings"
    )
    op.drop_index("idx_tech_drawing_sort", table_name="technical_drawings")
    op.drop_index(
        "idx_tech_drawing_product_view", table_name="technical_drawings"
    )
    op.drop_table("technical_drawings")
    op.drop_index(op.f("ix_size_charts_is_deleted"), table_name="size_charts")
    op.drop_index(op.f("ix_size_charts_id"), table_name="size_charts")
    op.drop_table("size_charts")
    op.drop_index(
        op.f("ix_product_variants_sku"), table_name="product_variants"
    )
    op.drop_index(
        op.f("ix_product_variants_product_id"), table_name="product_variants"
    )
    op.drop_index(
        op.f("ix_product_variants_is_deleted"), table_name="product_variants"
    )
    op.drop_index(
        op.f("ix_product_variants_is_available"), table_name="product_variants"
    )
    op.drop_index(
        op.f("ix_product_variants_id"), table_name="product_variants"
    )
    op.drop_index(
        op.f("ix_product_variants_color"), table_name="product_variants"
    )
    op.drop_index("idx_variant_sort", table_name="product_variants")
    op.drop_index("idx_variant_product_color", table_name="product_variants")
    op.drop_index("idx_variant_available", table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index(op.f("ix_files_product_id"), table_name="files")
    op.drop_index(op.f("ix_files_is_deleted"), table_name="files")
    op.drop_index(op.f("ix_files_id"), table_name="files")
    op.drop_index(op.f("ix_files_hash_sha256"), table_name="files")
    op.drop_index(op.f("ix_files_hash_md5"), table_name="files")
    op.drop_index(op.f("ix_files_filename"), table_name="files")
    op.drop_index(op.f("ix_files_content_type"), table_name="files")
    op.drop_index(op.f("ix_files_collection_id"), table_name="files")
    op.drop_index("idx_file_size", table_name="files")
    op.drop_index("idx_file_product", table_name="files")
    op.drop_index("idx_file_created", table_name="files")
    op.drop_index("idx_file_content_type", table_name="files")
    op.drop_index("idx_file_collection", table_name="files")
    op.drop_table("files")
    op.drop_index(op.f("ix_products_status"), table_name="products")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_is_featured"), table_name="products")
    op.drop_index(op.f("ix_products_is_deleted"), table_name="products")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_index(op.f("ix_products_collection_id"), table_name="products")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_index("idx_product_collection_status", table_name="products")
    op.drop_index("idx_product_category_featured", table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_is_deleted"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_firebase_uid"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("idx_user_role_active", table_name="users")
    op.drop_index("idx_user_email_active", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_collections_year"), table_name="collections")
    op.drop_index(op.f("ix_collections_status"), table_name="collections")
    op.drop_index(op.f("ix_collections_slug"), table_name="collections")
    op.drop_index(op.f("ix_collections_season"), table_name="collections")
    op.drop_index(op.f("ix_collections_name"), table_name="collections")
    op.drop_index(
        op.f("ix_collections_is_published"), table_name="collections"
    )
    op.drop_index(op.f("ix_collections_is_deleted"), table_name="collections")
    op.drop_index(op.f("ix_collections_id"), table_name="collections")
    op.drop_index("idx_collection_status_published", table_name="collections")
    op.drop_index("idx_collection_season_year", table_name="collections")
    op.drop_index("idx_collection_order_dates", table_name="collections")
    op.drop_table("collections")
    # ### end Alembic commands ###
